security:
    password_hashers:
        App\Entity\Users: 'bcrypt'

    providers:
        users_in_database:
            entity:
                class: App\Entity\Users
                property: pseudo

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: users_in_database
            custom_authenticators:
                - App\Security\LoginAuthenticator
            form_login:
                login_path: app_conexion
                check_path: app_conexion
            logout:
                path: app_logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
